/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeasureParam } from './measureParam';
import { MeasureDispersionType } from './measureDispersionType';

export interface BaselineMeasure {
  title?: any | null;
  description?: any | null;
  populationDescription?: any | null;
  paramType?: MeasureParam;
  dispersionType?: MeasureDispersionType;
  unitOfMeasure?: any | null;
  calculatePct?: any | null;
  denomUnitsSelected?: any | null;
  denoms?: any | null;
  classes?: any | null;
}
export namespace BaselineMeasure {}
