/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldStatsType } from './fieldStatsType';

export interface BooleanStats {
  falseCount: any | null;
  field: any | null;
  missingStudiesCount: any | null;
  piece: any | null;
  trueCount: any | null;
  type: FieldStatsType;
}
export namespace BooleanStats {}
