/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrollmentInfo } from './enrollmentInfo';
import { ExpandedAccessTypes } from './expandedAccessTypes';
import { StudyType } from './studyType';
import { DesignInfo } from './designInfo';
import { BioSpec } from './bioSpec';

export interface DesignModule {
  studyType?: StudyType;
  nPtrsToThisExpAccNctId?: any | null;
  expandedAccessTypes?: ExpandedAccessTypes;
  patientRegistry?: any | null;
  targetDuration?: any | null;
  phases?: any | null;
  designInfo?: DesignInfo;
  bioSpec?: BioSpec;
  enrollmentInfo?: EnrollmentInfo;
}
export namespace DesignModule {}
