/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SamplingMethod } from './samplingMethod';
import { Sex } from './sex';

export interface EligibilityModule {
  eligibilityCriteria?: any | null;
  healthyVolunteers?: any | null;
  sex?: Sex;
  genderBased?: any | null;
  genderDescription?: any | null;
  minimumAge?: any | null;
  maximumAge?: any | null;
  stdAges?: any | null;
  studyPopulation?: any | null;
  samplingMethod?: SamplingMethod;
}
export namespace EligibilityModule {}
