/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FieldNode {
  altPieceNames?: any | null;
  children?: any | null;
  definition?: any | null;
  historicOnly?: any | null;
  indexedOnly?: any | null;
  isEnum?: any | null;
  maxChars?: any | null;
  name: any | null;
  nested?: any | null;
  piece: any | null;
  rules?: any | null;
  sourceType: any | null;
  synonyms?: any | null;
  title?: any | null;
  type: any | null;
}
