/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoPoint } from './geoPoint';
import { RecruitmentStatus } from './recruitmentStatus';

export interface Location {
  facility?: any | null;
  status?: RecruitmentStatus;
  city?: any | null;
  state?: any | null;
  zip?: any | null;
  country?: any | null;
  contacts?: any | null;
  geoPoint?: GeoPoint;
}
export namespace Location {}
