/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrollmentInfo } from './enrollmentInfo';
import { Outcome } from './outcome';
import { Sponsor } from './sponsor';
import { ResponsibleParty } from './responsibleParty';

export interface OriginalData {
  [key: string]: any | any;

  enrollmentCountSame?: any | null;
  enrollmentInfo?: EnrollmentInfo;
  leadSponsor?: Sponsor;
  leadSponsorSame?: any | null;
  orgFullName?: any | null;
  orgFullNameSame?: any | null;
  otherOutcomes?: Outcome;
  otherOutcomesSame?: any | null;
  primaryOutcomes?: Outcome;
  primaryOutcomesSame?: any | null;
  responsibleParty?: ResponsibleParty;
  responsiblePartySame?: any | null;
  secondaryOutcomes?: Outcome;
  secondaryOutcomesSame?: any | null;
}
