/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutcomeMeasureType } from './outcomeMeasureType';
import { MeasureParam } from './measureParam';
import { ReportingStatus } from './reportingStatus';

export interface OutcomeMeasure {
  type?: OutcomeMeasureType;
  title?: any | null;
  description?: any | null;
  populationDescription?: any | null;
  reportingStatus?: ReportingStatus;
  anticipatedPostingDate?: any | null;
  paramType?: MeasureParam;
  dispersionType?: any | null;
  unitOfMeasure?: any | null;
  calculatePct?: any | null;
  timeFrame?: any | null;
  typeUnitsAnalyzed?: any | null;
  denomUnitsSelected?: any | null;
  groups?: any | null;
  denoms?: any | null;
  classes?: any | null;
  analyses?: any | null;
}
export namespace OutcomeMeasure {}
