/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProfileResults {
  [key: string]: any | any;

  aggLuceneQuery?: any | null;
  aggTime?: any | null;
  elasticRequestTime: any | null;
  elasticTookTime: any | null;
  luceneQuery?: any | null;
  postProcessTime: any | null;
  preProcessTime: any | null;
  topQueryTime?: any | null;
}
