/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactsLocationsModule } from './contactsLocationsModule';
import { EligibilityModule } from './eligibilityModule';
import { IpdSharingStatementModule } from './ipdSharingStatementModule';
import { StatusModule } from './statusModule';
import { OversightModule } from './oversightModule';
import { SponsorCollaboratorsModule } from './sponsorCollaboratorsModule';
import { ArmsInterventionsModule } from './armsInterventionsModule';
import { DescriptionModule } from './descriptionModule';
import { ConditionsModule } from './conditionsModule';
import { DesignModule } from './designModule';
import { IdentificationModule } from './identificationModule';
import { ReferencesModule } from './referencesModule';
import { OutcomesModule } from './outcomesModule';

export interface ProtocolSection {
  identificationModule?: IdentificationModule;
  statusModule?: StatusModule;
  sponsorCollaboratorsModule?: SponsorCollaboratorsModule;
  oversightModule?: OversightModule;
  descriptionModule?: DescriptionModule;
  conditionsModule?: ConditionsModule;
  designModule?: DesignModule;
  armsInterventionsModule?: ArmsInterventionsModule;
  outcomesModule?: OutcomesModule;
  eligibilityModule?: EligibilityModule;
  contactsLocationsModule?: ContactsLocationsModule;
  referencesModule?: ReferencesModule;
  ipdSharingStatementModule?: IpdSharingStatementModule;
}
