/**
 * ClinicalTrials.gov REST API
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Study } from './study';
import { ExtraHighlights } from './extraHighlights';
import { Explanation } from './explanation';
import { StudyColumns } from './studyColumns';

export interface SearchHit {
  [key: string]: any | any;

  columns?: StudyColumns;
  explanation?: Explanation;
  extraHighlights?: ExtraHighlights;
  id: any | null;
  isNew: any | null;
  score?: any | null;
  study?: Study;
}
