import { Component, Input } from '@angular/core';
import {
  ACTIVE_NOT_RECRUITING,
  APPROVED_FOR_MARKETING,
  AVAILABLE,
  COMPLETED,
  ENROLLING_BY_INVITATION,
  NO_LONGER_AVAILABLE,
  NOT_YET_RECRUITING,
  OVERALL_STATUS,
  RECRUITING,
  SUSPENDED,
  TEMPORARILY_NOT_AVAILABLE,
  TERMINATED,
  UNKNOWN,
  WITHDRAWN,
  WITHHELD,
} from '../../models/study';
import { Status } from '../../models/external-api/status';

@Component({
  selector: 'app-status',
  templateUrl: './status.component.html',
})
export class StatusComponent {
  ACTIVE_NOT_RECRUITING: ACTIVE_NOT_RECRUITING = 'ACTIVE_NOT_RECRUITING';
  COMPLETED: COMPLETED = 'COMPLETED';
  ENROLLING_BY_INVITATION: ENROLLING_BY_INVITATION = 'ENROLLING_BY_INVITATION';
  NOT_YET_RECRUITING: NOT_YET_RECRUITING = 'NOT_YET_RECRUITING';
  RECRUITING: RECRUITING = 'RECRUITING';
  SUSPENDED: SUSPENDED = 'SUSPENDED';
  TERMINATED: TERMINATED = 'TERMINATED';
  WITHDRAWN: WITHDRAWN = 'WITHDRAWN';
  AVAILABLE: AVAILABLE = 'AVAILABLE';
  NO_LONGER_AVAILABLE: NO_LONGER_AVAILABLE = 'NO_LONGER_AVAILABLE';
  TEMPORARILY_NOT_AVAILABLE: TEMPORARILY_NOT_AVAILABLE = 'TEMPORARILY_NOT_AVAILABLE';
  APPROVED_FOR_MARKETING: APPROVED_FOR_MARKETING = 'APPROVED_FOR_MARKETING';
  WITHHELD: WITHHELD = 'WITHHELD';
  UNKNOWN: UNKNOWN = 'UNKNOWN';

  @Input() status: OVERALL_STATUS | Status = 'UNKNOWN';
}
